name: setup-ollama
description: Setup Ollama on a hosted linux runner
inputs:
  override_conf:
    description: override.conf for ollama.service
    required: false
    default: |
      [Service]
      Environment="OLLAMA_CONTEXT_LENGTH=32768"
      Environment="OLLAMA_DEBUG=1"
      Environment="OLLAMA_KEEP_ALIVE=-1"
      Environment="OLLAMA_MAX_LOADED_MODELS=1"
      Environment="OLLAMA_NUM_PARALLEL=1"
      Environment="OLLAMA_ORIGINS=*"
runs:
  using: composite
  steps:
    - if: ${{ runner.os == 'Linux' }}
      run: |
        curl -fsSL https://ollama.com/install.sh | sh

        if [[ $OVERRIDE_CONF != "" ]]; then
          sudo mkdir -p /etc/systemd/system/ollama.service.d
          echo "$OVERRIDE_CONF" | sudo tee /etc/systemd/system/ollama.service.d/override.conf

          sudo systemctl daemon-reload
          sudo systemctl restart ollama.service
        fi
      shell: bash
      env:
        OVERRIDE_CONF: ${{ inputs.override_conf }}
