name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup-ollama
        uses: ./

      - name: test-ollama
        run: |
          ollama run hf.co/unsloth/Qwen3-14B-GGUF:IQ3_XXS "/no_think write a simple forth interpreter in haskell, don't do parsing" --verbose
